services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-local}
    container_name: sponge-app
    ports:
      - '80:${PORT}'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
    restart: unless-stopped
    networks:
      - sponge-network

networks:
  sponge-network:
    driver: bridge
